name: Release Helm Chart
on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
